title: "freshgum's page" # name of the site
author: freshgum bubbles # name of site's author
email: freshgum.bubbles@protonmail.com # email of site's author
url: https://freshgum.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  Privacy researcher, programmer, web developer. Nuance is paramount.

collections_dir: collections
collections:
  posts:
    output: true
  experiments:
    output: true

defaults:
  - scope:
      path: ""
    values:
      # Enable the TOC for every post.
      toc: true
      heading_anchors: true

# permalink: /slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  # See See _data/tweaks.yml for details.
  tweaks: true

  meta_theme_color: true

  # The default heading displayed via the header include.
  default_heading: "in the life of freshgum..."

  # Darken drafted posts on the home-screen in development.
  theme_drafted_posts: true
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: "to be a freshgum" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  bio:
    show_on_homepage: true
    text: >
      I'm a developer interested in performance, TypeScript, everyday appliances, and UX / design.
      If I find something interesting, I'll probably write about it here; my hope for this website is that
      my random musings and explorations are able to teach you something, and possibly encourage you
      to delve into things you find interesting, too.

sass:
  # style: compressed
  sass_dir: _sass

assets:
  compression: true
  sources:
    - assets/images

jekyll-minifier:
  uglifier_args:
    harmony: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-toc
  - jekyll-assets
  - jekyll-minifier
  - jekyll-sass-converter

exclude:
  - .devbox
  - devbox.json
  - devbox.lock
  - "*.gemspec"